---
title: "A summary of the tweets generated at the 2019 CEFP workshop"
author: "Rayna M Harris"
output: md_document
---

```{r setup, echo=FALSE, warning=F, message=F}
## load rtweet and dplyr packages
library(rtweet)
library(dplyr)

# set default code output to False
knitr::opts_chunk$set(echo = F)
```


```{r fetch tweets, message=F}
## first, follow steps in <https://rtweet.info/> to setup API and relevant tokens

## search for 18000 tweets using the rstats hashtag
rt <- search_tweets(
  "#CEFP2019", n = 18000, include_rts = FALSE
)
```

### Basic summary

There were a total of **`r nrow(rt)`** tweets with the #CEFP2019 hashtag. These tweets were authored by **`r length(unique(rt$screen_name))`** different particpants.


```{r tweet_timeline}
# tweet timeline
ts_plot(rt, "2 hours") +
  ggplot2::theme_minimal() +
  ggplot2::theme(plot.title = ggplot2::element_text(face = "bold")) +
  ggplot2::labs(
    x = NULL, y = NULL,
    title = "Frequency of #CEFP tweets",
    subtitle = "Twitter status (tweet) counts aggregated using two-hour intervals",
    caption = "\nSource: Data collected from Twitter's REST API via rtweet"
  )

```


```{r top5fav}
# top 5 favorited 
rt %>%
  top_n(5, favorite_count) %>%
  arrange(desc(favorite_count)) %>%
  select(screen_name, text)
```

```{r top5favs}
top_fav <- rt %>%
    top_n(5, favorite_count) %>%
    arrange(desc(favorite_count))

render_tweet <- function(dt, row) {
    screen_name <- dt$screen_name[i]
    id <- format(dt$status_id[i], scientific = FALSE)
    txt <- dt$text[i]
    created <- format(dt$created_at[i], "%Y-%m-%d")
    n_fav <- dt$favorite_count[i]
    n_retweets <- dt$retweet_count[i]
    cat("<blockquote class=\"twitter-tweet\" lang=\"en\"> \n",
        "<p lang=\"en\" dir=\"ltr\">",
        txt,
        "</p>&mdash; ",
        "<a href=\"https://twitter.com/", screen_name, "\">", screen_name, "</a>", "&nbsp;|&nbsp;",
        "<a href=\"https://twitter.com/",
        screen_name, "/status/", id, "\"> ", created, "</a> &nbsp;|&nbsp;",
        n_retweets, " retweets, ",  n_fav, " favorites. </blockquote>",
        "\n \n",
        sep = "")
}
for (i in seq_len(nrow(top_fav))) {
    render_tweet(top_fav, i)
}
```


### Acknowledgment

This code was adapted from François Michonneau's [code](https://github.com/fmichonneau/2018-carpentrycon-tweets/blob/master/index.Rmd) that he used to create this [blog post about twitter statistics from Carpentry Con 2018](https://carpentries.org/2018/06/carpentrycon-tweets). The [`rtweet` package](https://rtweet.info/) had excellent documentation.